[package]
authors = ['Interlay Ltd']
description = 'Redeem module'
edition = '2018'
name = 'redeem'
version = '0.4.0'

[dependencies]
serde = { version = "1.0.101", default-features = false, features = ['derive'], optional = true }
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ['derive'] }
primitive-types = { version = "0.7.2", default-features = false, features = ["codec"] }
sha2 = { version = "0.8.0", default-features = false }

# Substrate dependencies
sp-io = { version = "2.0.0", default-features = false }
sp-core = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }
sp-arithmetic = { version = "2.0.0", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false }

frame-support = { version = "2.0.0", default-features = false }
frame-system = { version = "2.0.0", default-features = false }
frame-benchmarking = { version = "2.0.0", default-features = false, optional = true }
pallet-balances = { version = "2.0.0", default-features = false }
pallet-timestamp = { version = "2.0.0", default-features = false }

# Parachain dependencies
bitcoin = { path = "../bitcoin", default-features = false }
btc-relay = { path = "../btc-relay", default-features = false }
collateral = { path = "../collateral", default-features = false }
exchange-rate-oracle = { path = "../exchange-rate-oracle", default-features = false }
fee = { path = "../fee", default-features = false }
security = { path = "../security", default-features = false }
sla = { path = "../sla", default-features = false }
treasury = { path = "../treasury", default-features = false }
vault-registry = { path = "../vault-registry", default-features = false }
util = { path = "../util", default-features = false }

[dev-dependencies]
mocktopus = "0.7.0"
frame-benchmarking = { version = "2.0.0", default-features = false }
pallet-randomness-collective-flip = { version = "2.0.0", default-features = false }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"primitive-types/std",
	"sha2/std",
	"sp-io/std",
	"sp-core/std",
	"sp-std/std",
	"sp-arithmetic/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"frame-benchmarking/std",
	"pallet-balances/std",
	"pallet-timestamp/std",
	"bitcoin/std",
	"btc-relay/std",
	"collateral/std",
	"exchange-rate-oracle/std",
	"fee/std",
	"security/std",
	"sla/std",
	"treasury/std",
	"vault-registry/std",
	"util/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
]