[package]
authors = ["Interlay Ltd"]
edition = "2021"
name = 'interbtc-runtime-standalone'
version = "1.2.0"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
serde = { version = "1.0.130", default-features = false, features = ["derive"], optional = true }
codec = { package = "parity-scale-codec", version = "3.1.5", default-features = false, features = ["derive", "max-encoded-len"] }
hex-literal = { version = "0.3.1", optional = true }
scale-info = { version = "2.2.0", default-features = false, features = ["derive"] }

# Substrate dependencies
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-version = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }

frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
frame-executive = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false, optional = true }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-sudo = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-utility = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-scheduler = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-multisig = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-preimage = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-identity = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-proxy = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }

frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }

## Governance
pallet-collective = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-membership = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-society = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }

# Aura & GRANDPA dependencies
pallet-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-aura = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }
pallet-authorship = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31", default-features = false }

# Parachain dependencies
runtime-common = {path = "../../parachain/runtime/common", default-features = false }
btc-relay = { path = "../../crates/btc-relay", default-features = false }
currency = { path = "../../crates/currency", default-features = false }
security = { path = "../../crates/security", default-features = false }
vault-registry = { path = "../../crates/vault-registry", default-features = false }
oracle = { path = "../../crates/oracle", default-features = false }
fee = { path = "../../crates/fee", default-features = false }
issue = { path = "../../crates/issue", default-features = false }
redeem = { path = "../../crates/redeem", default-features = false }
replace = { path = "../../crates/replace", default-features = false }
nomination = { path = "../../crates/nomination", default-features = false }
reward = { path = "../../crates/reward", default-features = false }
staking = { path = "../../crates/staking", default-features = false }
escrow = { path = "../../crates/escrow", default-features = false }
democracy = { path = "../../crates/democracy", default-features = false }
annuity = { path = "../../crates/annuity", default-features = false }
supply = { path = "../../crates/supply", default-features = false }
clients-info = { path = "../../crates/clients-info", default-features = false }
loans = { path = "../../crates/loans", default-features = false }
traits = { path = "../../crates/traits", default-features = false }
farming = { path = "../../crates/farming", default-features = false }
tx-pause = { path = "../../crates/tx-pause", default-features = false }
dex-general = { path = "../../crates/dex-general", default-features = false }

primitives = { package = "interbtc-primitives", path = "../../primitives", default-features = false }

btc-relay-rpc-runtime-api = { path = "../../crates/btc-relay/rpc/runtime-api", default-features = false }
oracle-rpc-runtime-api = { path = "../../crates/oracle/rpc/runtime-api", default-features = false }
vault-registry-rpc-runtime-api = { path = "../../crates/vault-registry/rpc/runtime-api", default-features = false }
escrow-rpc-runtime-api = { path = "../../crates/escrow/rpc/runtime-api", default-features = false }
reward-rpc-runtime-api = { path = "../../crates/reward/rpc/runtime-api", default-features = false }
issue-rpc-runtime-api = { path = "../../crates/issue/rpc/runtime-api", default-features = false }
redeem-rpc-runtime-api = { path = "../../crates/redeem/rpc/runtime-api", default-features = false }
replace-rpc-runtime-api = { path = "../../crates/replace/rpc/runtime-api", default-features = false }
loans-rpc-runtime-api = { path = "../../crates/loans/rpc/runtime-api", default-features = false }
dex-general-rpc-runtime-api = { path = "../../crates/dex-general/rpc/runtime-api", default-features = false }
dex-stable-rpc-runtime-api = { path = "../../crates/dex-stable/rpc/runtime-api", default-features = false }

# Orml dependencies
orml-tokens = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "dc39cfddefb10ef0de23655e2c3dcdab66a19404", default-features = false }
orml-traits = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "dc39cfddefb10ef0de23655e2c3dcdab66a19404", default-features = false }
orml-vesting = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "dc39cfddefb10ef0de23655e2c3dcdab66a19404", default-features = false }
orml-asset-registry = { git = "https://github.com/open-web3-stack/open-runtime-module-library", rev = "dc39cfddefb10ef0de23655e2c3dcdab66a19404", default-features = false }

xcm-builder = { git = "https://github.com/paritytech/polkadot", branch = "release-v0.9.31", default-features = false }

[dev-dependencies]
hex = "0.4.2"
mocktopus = "0.8.0"
serde_json = "1.0"
pretty_assertions = "0.7.2"
flate2= "1.0"
itertools = "0.10.0"

bitcoin = { path = "../../crates/bitcoin", default-features = false }

vault-registry = { path = "../../crates/vault-registry", default-features = false, features = ["integration-tests"]}
rand = "0.8.5"
log = { version = "0.4.14", default-features = false }
env_logger = {version = "0.9.1" }

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.31" }

[features]
default = ["std"]
std = [
  "serde",
  "codec/std",

  "sp-std/std",
  "sp-api/std",
  "sp-io/std",
  "sp-version/std",
  "sp-runtime/std",
  "sp-core/std",
  "sp-session/std",
  "sp-offchain/std",
  "sp-block-builder/std",
  "sp-transaction-pool/std",
  "sp-inherents/std",
  "sp-arithmetic/std",

  "frame-support/std",
  "frame-executive/std",
  "frame-system/std",
  "frame-benchmarking/std",
  "pallet-balances/std",
  "pallet-timestamp/std",
  "pallet-sudo/std",
  "pallet-utility/std",
  "pallet-transaction-payment/std",
  "pallet-scheduler/std",
  "pallet-multisig/std",
  "pallet-preimage/std",
  "pallet-identity/std",
  "pallet-proxy/std",

  "pallet-collective/std",
  "pallet-membership/std",
  "pallet-society/std",

  "frame-system-rpc-runtime-api/std",
  "pallet-transaction-payment-rpc-runtime-api/std",

  "pallet-grandpa/std",
  "pallet-aura/std",
  "sp-consensus-aura/std",
  "pallet-authorship/std",

  "runtime-common/std",
  "btc-relay/std",
  "currency/std",
  "security/std",
  "vault-registry/std",
  "oracle/std",
  "fee/std",
  "issue/std",
  "redeem/std",
  "replace/std",
  "nomination/std",
  "reward/std",
  "staking/std",
  "escrow/std",
  "democracy/std",
  "annuity/std",
  "supply/std",
  "loans/std",
  "traits/std",
  "farming/std",
  "tx-pause/std",
  "dex-general/std",

  "primitives/std",

  "btc-relay-rpc-runtime-api/std",
  "oracle-rpc-runtime-api/std",
  "vault-registry-rpc-runtime-api/std",
  "escrow-rpc-runtime-api/std",
  "reward-rpc-runtime-api/std",
  "issue-rpc-runtime-api/std",
  "redeem-rpc-runtime-api/std",
  "replace-rpc-runtime-api/std",
  "loans-rpc-runtime-api/std",
  "dex-general-rpc-runtime-api/std",
  "dex-stable-rpc-runtime-api/std",

  "orml-asset-registry/std",
  "orml-tokens/std",
  "orml-traits/std",
  "orml-vesting/std",

  "xcm-builder/std",

  "currency/testing-utils",
  "fee/integration-tests",
  "staking/integration-tests",
  "loans/integration-tests",
]
runtime-benchmarks = [
  "hex-literal",

  "frame-benchmarking",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",

  "pallet-collective/runtime-benchmarks",
  "pallet-society/runtime-benchmarks",

  "annuity/runtime-benchmarks",
  "btc-relay/runtime-benchmarks",
  "dex-general/runtime-benchmarks",
  "escrow/runtime-benchmarks",
  "fee/runtime-benchmarks",
  "issue/runtime-benchmarks",
  "loans/runtime-benchmarks",
  "nomination/runtime-benchmarks",
  "oracle/runtime-benchmarks",
  "redeem/runtime-benchmarks",
  "replace/runtime-benchmarks",
  "vault-registry/runtime-benchmarks",
  "farming/runtime-benchmarks",
  "tx-pause/runtime-benchmarks",

  "orml-asset-registry/runtime-benchmarks",

  "xcm-builder/runtime-benchmarks",
]
disable-runtime-api = []
skip-slow-tests = []
