[package]
authors = ["Interlay Ltd"]
edition = "2018"
name = "module-vault-registry-rpc"
version = "2.0.0-rc6"

[dependencies]
codec = {package = "parity-scale-codec", version = '1.3.4'}
jsonrpc-core = "14.0.5"
jsonrpc-core-client = "14.0.5"
jsonrpc-derive = "14.0.5"
module-vault-registry-rpc-runtime-api = {path = "runtime-api"}
serde = {version = "1.0.101", features = ["derive"]}
sp-api = {version = "2.0.0-rc6"}
sp-blockchain = {version = "2.0.0-rc6"}
sp-runtime = {version = "2.0.0-rc6"}
