[package]
authors = ["Interlay Ltd"]
edition = "2018"
name = "btc-parachain-primitives"
version = "0.7.0"

[dependencies]
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3", default-features = false }

# Parachain dependencies
bitcoin = { path = "../crates/bitcoin", default-features = false }
issue = { path = "../crates/issue", default-features = false }
redeem = { path = "../crates/redeem", default-features = false }
replace = { path = "../crates/replace", default-features = false }
refund = { path = "../crates/refund", default-features = false }

[features]
default = ["std"]
std = [
    "sp-core/std",
    "sp-runtime/std",

    "bitcoin/std",
    "issue/std",
    "redeem/std",
    "replace/std",
    "refund/std",
]