[package]
name = "vault-registry"
version = "0.1.0"
authors = ["Interlay Ltd"]
edition = "2018"

[features]
default = ['std']
std = [
  'serde',
  'codec/std',
  'primitive-types/std',
  'frame-support/std',
  'sp-runtime/std',
  'sp-arithmetic/std',
  'sp-std/std',
  'sp-io/std',
  'system/std',
  'timestamp/std',
  'sp-core/std',
  'pallet-balances/std',
  'x-core/std',
  'collateral/std',
  'treasury/std',
  'security/std',
  'exchange-rate-oracle/std',
]

[dependencies.serde]
version = '1.0.101'
features = ['derive']
optional = true

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.0'

[dependencies.primitive-types]
default-features = false
version = '0.7.2'
features= ['codec']

[dependencies.sp-std]
default-features = false
version = '2.0.0-alpha.7'

[dependencies.sp-runtime]
default-features = false
version = '2.0.0-alpha.7'

[dependencies.sp-arithmetic]
default-features = false
version = '2.0.0-alpha.7'

[dependencies.frame-support]
default-features = false
version = '2.0.0-alpha.7'

[dependencies.system]
default-features = false
package = 'frame-system'
version = '2.0.0-alpha.7'

[dependencies.sp-io]
default-features = false
version = '2.0.0-alpha.7'

[dependencies.sp-core]
default-features = false
version = '2.0.0-alpha.7'

[dependencies.timestamp]
default-features = false
package = 'pallet-timestamp'
version = '2.0.0-alpha.7'

[dependencies.pallet-balances]
default-features = false
package = 'pallet-balances'
version = '2.0.0-alpha.7'

[dependencies.x-core]
default-features = false
path = '../x-core'

[dependencies.security]
default-features = false
path = '../security'

[dependencies.collateral]
default-features = false
path = '../collateral'

[dependencies.treasury]
default-features = false
path = '../treasury'

[dependencies.exchange-rate-oracle]
default-features = false
path = '../exchange-rate-oracle'

[dev-dependencies]
mocktopus = "0.7.0"
