image: "registry.gitlab.com/interlay/containers/rust-base:nightly-2021-01-25"

.rust-before-script: &rustup_sscache
  before_script:
    - rustup show
    - rustc --version
    - rustfmt --version
    - cargo --version
    - SCCACHE_START_SERVER=1 SCCACHE_IDLE_TIMEOUT=0 sccache
    - sccache -s

# Declare stages
stages:
    - build # for builds & tests
    - deploy # for deployment

build-standalone:
    stage: build
    variables:
        CARGO_HOME: $CI_PROJECT_DIR/.cargo
        RUSTC_WRAPPER: /usr/local/bin/sccache
        ARTIFACT_BIN_PATH: btc-parachain
    <<: *rustup_sscache
    script:
        - cargo fmt -- --check
        - cargo check --all
        - cargo test --all
        - cargo build --release
        - sccache -s
    artifacts:
        name: "${CI_COMMIT_REF_SLUG}-standalone"
        paths:
            - target/release/${ARTIFACT_BIN_PATH}
    only:
        - tags
        - merge_requests
        - master
        - dev
        - alpha

build-parachain:
    stage: build
    variables:
        CARGO_HOME: $CI_PROJECT_DIR/.cargo
        RUSTC_WRAPPER: /usr/local/bin/sccache
        ARTIFACT_BIN_PATH: btc-parachain
    <<: *rustup_sscache
    script:
        - cargo check --manifest-path parachain/Cargo.toml --release --no-default-features --features cumulus-polkadot
        - cargo build --manifest-path parachain/Cargo.toml --release --no-default-features --features cumulus-polkadot
        - sccache -s
    artifacts:
        name: "${CI_COMMIT_REF_SLUG}-parachain"
        paths:
            - target/release/${ARTIFACT_BIN_PATH}
    only:
        - tags
        - merge_requests
        - master
        - dev
        - alpha

docker-publish-standalone:
    stage: deploy
    dependencies: 
        - build-standalone
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    script:
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        - |
            /kaniko/executor \
            --build-arg BINARY=btc-parachain \
            --context ${CI_PROJECT_DIR} \
            --dockerfile ${CI_PROJECT_DIR}/Dockerfile_release \
            --destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA} \
            --destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
    only:
        - tags
        - master
        - dev
        - alpha
        - web # For pipelines created by using Run pipeline button in the GitLab UI, from the project’s CI/CD > Pipelines section.

docker-publish-parachain:
    stage: deploy
    dependencies: 
        - build-parachain
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    script:
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        - |
            /kaniko/executor \
            --build-arg BINARY=btc-parachain \
            --context ${CI_PROJECT_DIR} \
            --dockerfile ${CI_PROJECT_DIR}/Dockerfile_release \
            --destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA} \
            --destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-rococo
    only:
        - tags
        - master
        - dev
        - alpha
        - web # For pipelines created by using Run pipeline button in the GitLab UI, from the project’s CI/CD > Pipelines section.

