include:
    - project: interlay/tools/ci-scripts
      file: /gitlab-templates/rust-base-gitlab-ci.yaml
      ref: nightly-2021-01-25

variables:
    ARTIFACT_BIN_PATH: btc-parachain
    TOOLCHAIN_VERSION: nightly-2021-01-25

