# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "registry.gitlab.com/interlay/btc-parachain:ci"

variables:
    CARGO_HOME: $CI_PROJECT_DIR/.cargo
    RUSTC_WRAPPER: sccache
    SCCACHE_GCS_RW_MODE: READ_WRITE
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

before_script:
    - rustc --version
    - rustfmt --version
    - cargo --version
    - SCCACHE_START_SERVER=1 SCCACHE_NO_DAEMON=1 sccache &
    - sccache -s

after_script:
    - sccache -s

# Declare stages
stages:
    - build # for crates and pallets
    - test # for tests in dev
    - deploy # for deployment in master

# pallets and crates
test-pallets-and-crates:
    stage: test
    script:
        - cargo fmt -- --check
        - cargo check --all
        - cargo build --release --verbose
        - cargo test --all --release
    cache:
        key: cargo
        paths:
            - .cargo
    only:
        - merge_requests

docker-publish:
    stage: deploy
    image: docker:19.03.12
    services:
        - docker:19.03.12-dind
    before_script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    script:
        - docker pull $CI_REGISTRY_IMAGE:latest || true
        - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
        - docker push $CI_REGISTRY_IMAGE:latest
    only:
        - master
        - dev
