[workspace]
members = [
  "crates/btc-core",
  "crates/xclaim-core",
  "crates/bitcoin",
  "crates/btc-relay",
  "crates/security",
  "crates/exchange-rate-oracle",
  "crates/vault-registry",
  "crates/treasury",
  "crates/collateral",
  "crates/issue",
  "parachain",
  "parachain/runtime",
]
