[package]
authors = ['Interlay']
description = 'Treasury module'
edition = '2018'
name = 'treasury'
version = '2.0.0-rc6'

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'safe-mix/std',
	'sp-core/std',
	'sp-io/std',
	'sp-runtime/std',
	'sp-std/std',
    'frame-system/std',
	'pallet-balances/std',
]

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.4'

[dependencies.frame-support]
default-features = false
version = '2.0.0-rc6'

[dependencies.safe-mix]
default-features = false
version = '1.0.0'

[dependencies.sp-core]
default-features = false
version = '2.0.0-rc6'

[dependencies.sp-io]
default-features = false
version = '2.0.0-rc6'

[dependencies.sp-runtime]
default-features = false
version = '2.0.0-rc6'

[dependencies.sp-std]
default-features = false
version = '2.0.0-rc6'

[dependencies.frame-system]
default-features = false
version = '2.0.0-rc6'

[dependencies.pallet-balances]
default-features = false
package = 'pallet-balances'
version = '2.0.0-rc6'

[dev-dependencies]
mocktopus = "0.7.0"

