[package]
authors = ["Interlay Ltd"]
edition = "2018"
name = "interbtc-rpc"
version = "0.8.0"

[dependencies]
jsonrpc-core = "15.1.0"

# Parachain dependencies
module-btc-relay-rpc = { path = "../crates/btc-relay/rpc" }
module-exchange-rate-oracle-rpc = { path = "../crates/exchange-rate-oracle/rpc" }
module-relay-rpc = { path = "../crates/relay/rpc" }
module-vault-registry-rpc = { path = "../crates/vault-registry/rpc" }
module-issue-rpc = { path = "../crates/issue/rpc" }
module-redeem-rpc = { path = "../crates/redeem/rpc" }
module-replace-rpc = { path = "../crates/replace/rpc" }
module-refund-rpc = { path = "../crates/refund/rpc" }

primitives = { package = "interbtc-primitives", path = "../primitives" }

# Substrate dependencies
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }

pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.7" }
