[package]
authors = ["Interlay Ltd"]
edition = "2018"
name = "btc-parachain-rpc"
version = "0.7.0"

[dependencies]
jsonrpc-core = "15.1.0"

# Parachain dependencies
module-btc-relay-rpc = { path = "../../crates/btc-relay/rpc" }
module-exchange-rate-oracle-rpc = { path = "../../crates/exchange-rate-oracle/rpc" }
module-staked-relayers-rpc = { path = "../../crates/staked-relayers/rpc" }
module-vault-registry-rpc = { path = "../../crates/vault-registry/rpc" }
module-issue-rpc = { path = "../../crates/issue/rpc" }
module-redeem-rpc = { path = "../../crates/redeem/rpc" }
module-replace-rpc = { path = "../../crates/replace/rpc" }
module-refund-rpc = { path = "../../crates/refund/rpc" }

primitives = { package = "btc-parachain-primitives", path = "../../primitives" }

# Substrate dependencies
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5" }

pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.5" }
