[package]
authors = ["Interlay Ltd"]
edition = "2021"
name = "module-reward-rpc"
version = '0.3.0'

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0" }
jsonrpsee = { version = "0.15.1", features = ["server", "macros"] }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29" }
module-reward-rpc-runtime-api = { path = "runtime-api" }

[dependencies.module-oracle-rpc-runtime-api]
path = '../../oracle/rpc/runtime-api'
