[package]
name = 'bitcoin'
version = '0.3.1'
authors = ['Interlay Ltd']
edition = '2018'

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ['derive'] }
serde = { version = "1.0.101", default-features = false, features = ['derive'], optional = true }
primitive-types = { version = "0.7.2", default-features = false, features = ["codec"] }
sha2 = { version = "0.8.2", default-features = false }
hex = { version = "0.4.2", default-features = false }
bitcoin_hashes = { version = "0.7.3", default-features = false }

# Substrate dependencies
sp-core = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }
frame-support = { version = "2.0.0", default-features = false }

[dev-dependencies]
mocktopus = '0.7.0'

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"primitive-types/std",
	"sha2/std",
	"hex/std",
	"sp-core/std",
	"sp-std/std",
	"frame-support/std",
]
