[package]
name = 'bitcoin'
version = '0.1.1'
authors = ['Interlay Ltd <dominik@interlay.io>']
edition = '2018'

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0.101'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.4'

[dependencies.primitive-types]
default-features = false
version = '0.7.2'
features= ['codec']

[dependencies.frame-support]
default-features = false
version = '2.0.0-rc6'

[dependencies.sp-std]
default-features = false
version = '2.0.0-rc6'

[dependencies.sp-core]
default-features = false
version = '2.0.0-rc6'

[dependencies.sha2]
default-features = false
version = '0.8.1'

[dependencies.hex]
default-features = false
version = '0.4.2'

[dependencies.bitcoin_hashes]
default-features = false
version = "0.7.3"

[dev-dependencies]
mocktopus = '0.7.0'

[features]
default = ['std']
std = [
	'serde',
	'codec/std',
	'primitive-types/std',
	'frame-support/std',
	'sp-std/std',
	'sp-core/std',
	'sha2/std',
	'hex/std',
]
