[package]
name = 'bitcoin'
version = '0.1.0'
authors = ['Interlay Ltd <dominik@interlay.io>']
edition = '2018'

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0.101'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.0.0'

[dependencies.primitive-types]
default-features = false
version = '0.6.2'
features= ['codec']

[dependencies.sp-std]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.sp-core]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.sha2]
default-features = false
version = "0.8.1"

[dependencies.btc-core]
default-features = false
path = '../btc-core'

[dependencies.hex]
default-features = false
version = '0.4.2'

[features]
default = ['std']
std = [
	'serde',
	'codec/std',
	'primitive-types/std',
	'sp-std/std',
	'sp-core/std',
	'sha2/std',
	'btc-core/std',
	'hex/std',
]