name: polkabtc
description: Helm chart for PolkaBTC

type: application
apiVersion: v2
version: 0.1.1
appVersion: 2.0.0-rc6

home: https://interlay.io/
sources:
    - https://gitlab.com/interlay/btc-parachain
maintainers:
    - name: Interlay
      email: contact@interlay.io
