[package]
name = "security"
version = "2.0.0-rc6"
authors = ["Interlay Ltd"]
edition = "2018"

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0.101'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.4'

[dependencies.frame-support]
default-features = false
version = '2.0.0-rc6'

[dependencies.frame-system]
default-features = false
version = '2.0.0-rc6'

[dependencies.sp-core]
default-features = false
version = '2.0.0-rc6'

[dependencies.sp-std]
default-features = false
version = '2.0.0-rc6'

[dependencies.primitive-types]
default-features = false
version = '0.7.2'
features= ['codec']

[dependencies.sha2]
default-features = false
version = '0.8.0'

[dependencies.x-core]
default-features = false
path = '../x-core'

[dev-dependencies.sp-runtime]
default-features = false
version = '2.0.0-rc6'

[dev-dependencies.sp-io]
default-features = false
version = '2.0.0-rc6'

[dev-dependencies]
mocktopus = '0.7.0'

[features]
default = ['std']
std = [
  'serde',
  'codec/std',
  'frame-support/std',
  'frame-system/std',
  'sp-core/std',
  'sp-std/std',
  'primitive-types/std',
  'sha2/std',
  'x-core/std'
]