[package]
name = "security"
version = "0.1.0"
authors = ["Interlay Ltd"]
edition = "2018"

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0.101'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.0.0'

[dependencies.frame-support]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.system]
default-features = false
package = 'frame-system'
version = '2.0.0-alpha.5'

[dependencies.sp-core]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.sp-std]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.primitive-types]
default-features = false
version = '0.7.0'
features= ['codec']

[dependencies.sha2]
default-features = false
version = '0.8.0'

[dev-dependencies.sp-runtime]
default-features = false
version = '2.0.0-alpha.5'

[dev-dependencies.sp-io]
default-features = false
version = '2.0.0-alpha.5'

[dev-dependencies]
mocktopus = '0.7.0'

[features]
default = ['std']
std = [
  'serde',
  'codec/std',
  'frame-support/std',
  'system/std',
  'sp-core/std',
  'sp-std/std',
  'primitive-types/std',
  'sha2/std',
]