[package]
authors = ['Interlay Ltd']
edition = '2018'
name = 'btc-parachain-service'
version = '0.5.1'

[dependencies]

# Parachain dependencies
btc-parachain-runtime = { path = "../runtime" }
btc-parachain-rpc = { path = "../rpc" }

# Substrate dependencies
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-executor = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", features = ["wasmtime"] }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-informant = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-session = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-offchain = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

# Cumulus dependencies
cumulus-consensus = { package = "cumulus-client-consensus-relay-chain", git = "https://github.com/paritytech/cumulus", branch = "rococo-v1", optional = true }
cumulus-network = { package = "cumulus-client-network", git = "https://github.com/paritytech/cumulus", branch = "rococo-v1", optional = true }
cumulus-primitives = { package = "cumulus-primitives-core", git = "https://github.com/paritytech/cumulus", branch = "rococo-v1", optional = true }
cumulus-service = { package = "cumulus-client-service", git = "https://github.com/paritytech/cumulus", branch = "rococo-v1", optional = true }
rococo-primitives = { package = "rococo-parachain-primitives", git = "https://github.com/paritytech/cumulus", branch = "rococo-v1", optional = true }

# Polkadot dependencies
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1", optional = true }
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1", optional = true }

[features]
cumulus-polkadot = [
    "cumulus-consensus",
    "cumulus-network",
    "cumulus-primitives",
    "cumulus-service",
    "rococo-primitives",
    "polkadot-primitives",
    "polkadot-service",
    
    "btc-parachain-runtime/cumulus-polkadot",
    "btc-parachain-rpc/cumulus-polkadot",
]
aura-grandpa = [
    "btc-parachain-runtime/aura-grandpa",
    "btc-parachain-rpc/aura-grandpa",
]
