[package]
name = "staked-relayers"
version = '0.2.2'
authors = ["Interlay Ltd"]
edition = "2018"

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0.101'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.4'

[dependencies.sp-runtime]
default-features = false
version = '2.0.0'

[dependencies.frame-support]
default-features = false
version = '2.0.0'

[dependencies.frame-system]
default-features = false
version = '2.0.0'

[dependencies.sp-io]
default-features = false
version = '2.0.0'

[dependencies.sp-core]
default-features = false
version = '2.0.0'

[dependencies.pallet-timestamp]
default-features = false
version = '2.0.0'

[dependencies.sp-std]
default-features = false
version = '2.0.0'

[dependencies.primitive-types]
default-features = false
version = '0.7.2'
features= ['codec']

[dependencies.bitcoin]
default-features = false
path = '../bitcoin'

[dependencies.collateral]
default-features = false
path = '../collateral'

[dependencies.vault-registry]
default-features = false
path = '../vault-registry'

[dependencies.security]
default-features = false
path = '../security'

[dependencies.treasury]
default-features = false
path = '../treasury'

[dependencies.exchange-rate-oracle]
default-features = false
path = '../exchange-rate-oracle'

[dependencies.btc-relay]
default-features = false
path = '../btc-relay'

[dependencies.redeem]
default-features = false
path = '../redeem'

[dependencies.replace]
default-features = false
path = '../replace'

[dependencies.sha2]
default-features = false
version = "0.8.2"

[dependencies.hex]
default-features = false
version = '0.4.2'

[dev-dependencies.pallet-balances]
default-features = false
version = '2.0.0'

[dependencies.frame-benchmarking]
version = "2.0.0"
default-features = false
optional = true

[dev-dependencies]
mocktopus = "0.7.0"
frame-benchmarking = { version = "2.0.0" }

[features]
default = ['std']
std = [
  'serde',
  'codec/std',
  'frame-support/std',
  'sp-runtime/std',
  'sp-io/std',
  'frame-system/std',
  'pallet-timestamp/std',
  'sp-core/std',
	'sp-std/std',
  'primitive-types/std',
  'bitcoin/std',
  'collateral/std',
  'vault-registry/std',
  'security/std',
  'treasury/std',
  'exchange-rate-oracle/std',
  'btc-relay/std',
  'redeem/std',
  'replace/std',
  'sha2/std',
  'hex/std',
  'frame-benchmarking/std',
]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
]
