[package]
name = "module-exchange-rate-oracle-rpc-runtime-api"
version = '0.3.0'
authors = ["Interlay Ltd"]
edition = "2018"

[dependencies]
codec = {package = "parity-scale-codec", version = '1.3.4', default-features = false, features = ["derive"]}
frame-support = {version = "2.0.0", default-features = false}
sp-api = {version = "2.0.0", default-features = false}
sp-std = {version = "2.0.0", default-features = false}
serde = {version = "1.0.101", features = ["derive"]}

[features]
default = ["std"]
std = [
  "codec/std",
  "sp-api/std",
  "sp-std/std",
  "frame-support/std",
]
