[package]
name = "module-exchange-rate-oracle-rpc-runtime-api"
version = "0.6.0"
authors = ["Interlay Ltd"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }

[features]
default = ["std"]
std = [
  "serde",
  "codec/std",
  "frame-support/std",
  "sp-api/std",
  "sp-std/std",
]
