[package]
authors = ['Interlay']
description = 'Replace module'
edition = '2018'
name = 'replace'
version = '0.1.0'

[dependencies.serde]
version = '1.0.101'
features = ['derive']
optional = true

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.0'

[dependencies.frame-support]
default-features = false
version = '2.0.0-alpha.7'

[dependencies.sp-core]
default-features = false
version = '2.0.0-alpha.7'

[dependencies.sp-io]
default-features = false
version = '2.0.0-alpha.7'

[dependencies.sp-runtime]
default-features = false
version = '2.0.0-alpha.7'

[dependencies.sp-std]
default-features = false
version = '2.0.0-alpha.7'

[dependencies.system]
default-features = false
package = 'frame-system'
version = '2.0.0-alpha.7'

[dependencies.pallet-balances]
default-features = false
package = 'pallet-balances'
version = '2.0.0-alpha.7'

[dependencies.primitive-types]
default-features = false
version = '0.7.2'
features= ['codec']

[dependencies.vault-registry]
default-features = false
path = '../vault-registry'

[dependencies.collateral]
default-features = false
path = '../collateral'

[dependencies.btc-relay]
default-features = false
path = '../btc-relay'

[dependencies.treasury]
default-features = false
path = '../treasury'

[dependencies.bitcoin]
default-features = false
path = '../bitcoin'

[dependencies.x-core]
default-features = false
path = '../x-core'

[dependencies.sha2]
default-features = false
version = '0.8.0'

[dependencies.security]
default-features = false
path = '../security'

[dependencies.timestamp]
default-features = false
package = 'pallet-timestamp'
version = '2.0.0-alpha.7'

[dev-dependencies]
mocktopus = '0.7.0'

[dev-dependencies.exchange-rate-oracle]
default-features = false
path = '../exchange-rate-oracle'

[features]
default = ['std']
std = [
	'serde',
	'codec/std',
	'frame-support/std',
	'sp-runtime/std',
	'sp-io/std',
	'sp-core/std',
	'system/std',
	'pallet-balances/std',
	'sp-std/std',
	'primitive-types/std',
	'vault-registry/std',
	'collateral/std',
	'btc-relay/std',
	'treasury/std',
	'bitcoin/std',
	'x-core/std',
	'sha2/std',
	'security/std',
	'timestamp/std',
]
