[package]
name = "x-core"
version = "0.1.0"
authors = ["Interlay Ltd"]
edition = "2018"

[dependencies.sp-std]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
tag = 'v2.0.0-alpha.7'

[dependencies.frame-support]
git = 'https://github.com/paritytech/substrate.git'
default-features = false
tag = 'v2.0.0-alpha.7'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.0'

[features]
default = ['std']
std = [
  'sp-std/std',
  'frame-support/std',
  'codec/std',
]
