[package]
authors = ["Interlay Ltd"]
edition = "2018"
name = "module-vault-registry-rpc-runtime-api"
version = '0.3.0'

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }

[dependencies.module-exchange-rate-oracle-rpc-runtime-api]
default-features = false
path = '../../../exchange-rate-oracle/rpc/runtime-api'

[features]
default = ["std"]
std = [
  "codec/std",
  "frame-support/std",
  "sp-api/std",
  "sp-std/std",
  "module-exchange-rate-oracle-rpc-runtime-api/std",
]
