[package]
authors = ["Interlay Ltd"]
edition = "2018"
name = "module-vault-registry-rpc-runtime-api"
version = '0.3.0'

[dependencies]
codec = { package = "parity-scale-codec", version = '1.3.4', default-features = false, features = ["derive"] }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }

[dependencies.module-exchange-rate-oracle-rpc-runtime-api]
default-features = false
path = '../../../exchange-rate-oracle/rpc/runtime-api'

[features]
default = ["std"]
std = [
  "codec/std",
  "frame-support/std",
  "sp-api/std",
  "sp-std/std",
  "module-exchange-rate-oracle-rpc-runtime-api/std",
]
