[package]
name = "exchange-rate-oracle"
version = "0.1.0"
authors = ["Interlay Ltd"]
edition = "2018"

[features]
default = ['std']
std = [
	'serde',
    'codec/std',
    'sp-runtime/std',
    'frame-support/std',
    'system/std',
    'sp-std/std',
    'sp-io/std',
    'sp-core/std',
    'timestamp/std',
    'pallet-balances/std',
    'x-core/std',
    'collateral/std',
    'treasury/std',
    'security/std',
]

[dependencies.serde]
version = '1.0.101'
features = ['derive']
optional = true

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.0.0'

[dependencies.sp-runtime]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.frame-support]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.system]
default-features = false
package = 'frame-system'
version = '2.0.0-alpha.5'

[dependencies.sp-std]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.sp-io]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.sp-core]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.timestamp]
default-features = false
package = 'pallet-timestamp'
version = '2.0.0-alpha.5'

[dependencies.pallet-balances]
default-features = false
package = 'pallet-balances'
version = '2.0.0-alpha.5'

[dependencies.x-core]
default-features = false
path = '../x-core'

[dependencies.collateral]
default-features = false
path = '../collateral'

[dependencies.treasury]
default-features = false
path = '../treasury'

[dependencies.security]
default-features = false
path = '../security'

[dev-dependencies]
mocktopus = "0.7.0"
