[package]
authors = ['Interlay']
description = 'Collateral module'
edition = '2018'
homepage = 'https://interlay.gitlab.io/polkabtc-spec/spec/collateral.html'
name = 'collateral'
version = '0.1.0'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.2.0'

[dependencies.frame-support]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.system]
default-features = false
package = 'frame-system'
version = '2.0.0-alpha.5'

[dev-dependencies.sp-core]
default-features = false
version = '2.0.0-alpha.5'

[dev-dependencies.sp-io]
default-features = false
version = '2.0.0-alpha.5'

[dev-dependencies.sp-runtime]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.pallet-balances]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.xclaim-core]
default-features = false
path = '../xclaim-core'

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'system/std',
    'xclaim-core/std',
    'pallet-balances/std',
]
