[package]
authors = ['Interlay']
description = 'SLA module'
edition = '2018'
name = 'sla'
version = '0.3.1'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.4'

[dependencies.frame-support]
default-features = false
version = '2.0.0'

[dependencies.sp-core]
default-features = false
version = '2.0.0'

[dependencies.sp-io]
default-features = false
version = '2.0.0'

[dependencies.sp-runtime]
default-features = false
version = '2.0.0'

[dependencies.sp-std]
default-features = false
version = '2.0.0'

[dependencies.frame-system]
default-features = false
version = '2.0.0'

[dependencies.pallet-balances]
default-features = false
package = 'pallet-balances'
version = '2.0.0'

[dependencies.serde]
version = '1.0.101'
features = ['derive']
optional = true

[dependencies.collateral]
default-features = false
path = '../collateral'

[dependencies.sp-arithmetic]
default-features = false
version = '2.0.0'

[dev-dependencies]
mocktopus = '0.7.0'

[features]
default = ['std']
std = [
	'serde',
	'codec/std',
	'frame-support/std',
	'sp-arithmetic/std',
	'sp-core/std',
	'sp-io/std',
	'sp-runtime/std',
	'collateral/std',
	'sp-std/std',
	'frame-system/std',
	'pallet-balances/std',
]