[package]
name = "module-staked-relayers-rpc-runtime-api"
version = '0.2.2'
authors = ["Interlay Ltd"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = '1.3.4', default-features = false, features = ["derive"] }
sp-api = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }
frame-support = { version = "2.0.0", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-api/std",
    "sp-std/std",
    "frame-support/std",
]