{{- define "settings" -}}
{{- range $.Values.environment.secrets }}
- name: {{ .name }}
  valueFrom:
    secretKeyRef:
      name: {{ .secret }}
      key: {{ .key }}
{{- end }}
{{- range $key, $val := $.Values.environment.inline }}
- name: {{ $key }}
  value: {{ $val | quote }}
{{- end }}
{{- end -}}