apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "polkabtc.fullname" . }}
  labels:
    {{- include "polkabtc.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "polkabtc.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "polkabtc.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "polkabtc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "polkabtc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - btc-parachain
            - --dev
            - --rpc-external
            - --ws-external
            - --base-path
            - {{ .Values.basePath }}-state
          env:
            {{- include "settings" $ | nindent 10 }}
          ports:
            - name: p2p
              containerPort: 30333
            - name: http-rpc
              containerPort: 9933
            - name: websocket-rpc
              containerPort: 9944
          volumeMounts:
          - name: {{ .Chart.Name }}-state
            mountPath: {{ .Values.basePath }}
          readinessProbe:
            httpGet:
              path: /health
              port: http-rpc
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http-rpc
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

  volumeClaimTemplates:
  - metadata:
      name: {{ .Chart.Name }}-state
    spec:
      accessModes:
        - {{ .Values.persistence.accessMode | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}

