[package]
name = "module-exchange-rate-oracle-rpc"
version = "2.0.0-rc6"
authors = ["Interlay Ltd"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", features = ["derive"] }
codec = { package = "parity-scale-codec", version = '1.3.4' }
jsonrpc-core = "14.0.5"
jsonrpc-core-client = "14.0.5"
jsonrpc-derive = "14.0.5"
sp-runtime = { version = "2.0.0-rc6" }
sp-api = { version = "2.0.0-rc6" }
sp-blockchain = { version = "2.0.0-rc6" }
module-exchange-rate-oracle-rpc-runtime-api = { path = "runtime-api" }
