[package]
authors = ['Interlay Ltd']
build = 'build.rs'
edition = '2018'
name = 'btc-parachain'
version = '0.3.0'

[features]
runtime-benchmarks = [
    "btc-parachain-runtime/runtime-benchmarks",
]

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[[bin]]
name = 'btc-parachain'

[dependencies]
jsonrpc-core = '15.0.0'
structopt = '0.3.8'
frame-benchmarking = "2.0.0"
frame-benchmarking-cli = '2.0.0'

[dependencies.btc-parachain-runtime]
path = './runtime'
version = '0.3.0'

[dependencies.pallet-transaction-payment-rpc]
version = '2.0.0'

[dependencies.sc-basic-authorship]
version = '0.8.0'

[dependencies.sc-cli]
features = ['wasmtime']
version = '0.8.0'

[dependencies.sc-client-api]
version = '2.0.0'

[dependencies.sc-consensus]
version = "0.8.0"

[dependencies.sc-consensus-aura]
version = '0.8.0'

[dependencies.sc-executor]
features = ['wasmtime']
version = '0.8.0'

[dependencies.sc-finality-grandpa]
version = '0.8.0'

[dependencies.sc-rpc]
version = '2.0.0'

[dependencies.sc-rpc-api]
version = '0.8.0'

[dependencies.sc-service]
features = ['wasmtime']
version = '0.8.0'

[dependencies.sc-transaction-pool]
version = '2.0.0'

[dependencies.sp-api]
version = '2.0.0'

[dependencies.sp-block-builder]
version = '2.0.0'

[dependencies.sp-blockchain]
version = '2.0.0'

[dependencies.sp-consensus]
version = '0.8.0'

[dependencies.sp-consensus-aura]
version = '0.8.0'

[dependencies.sp-core]
version = '2.0.0'

[dependencies.sp-finality-grandpa]
version = '2.0.0'

[dependencies.sp-inherents]
version = '2.0.0'

[dependencies.sp-runtime]
version = '2.0.0'

[dependencies.sp-transaction-pool]
version = '2.0.0'

[dependencies.substrate-frame-rpc-system]
version = '2.0.0'

[dependencies.module-exchange-rate-oracle-rpc]
path = "../crates/exchange-rate-oracle/rpc"

[dependencies.module-staked-relayers-rpc]
path = "../crates/staked-relayers/rpc"

[dependencies.module-vault-registry-rpc]
path = "../crates/vault-registry/rpc"

[dependencies.module-issue-rpc]
path = "../crates/issue/rpc"

[dependencies.module-redeem-rpc]
path = "../crates/redeem/rpc"

[dependencies.module-replace-rpc]
path = "../crates/replace/rpc"

[build-dependencies.substrate-build-script-utils]
version = '2.0.0'
