[package]
authors = ['Interlay Ltd']
build = 'build.rs'
edition = '2018'
name = 'btc-parachain'
version = '0.5.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[[bin]]
name = 'btc-parachain'

[build-dependencies.substrate-build-script-utils]
version = '2.0.0'

[dependencies]
structopt = "0.3.20"
log = '0.4.8'
codec = { package = 'parity-scale-codec', version = '1.0.0' }
serde = { version = "1.0.101", features = ["derive"] }
hex-literal = "0.2.1"

# Parachain dependencies
btc-parachain-runtime = { path = "./runtime" }
btc-parachain-service = { path = "./service" }
btc-parachain-rpc = { path = "./rpc" }

# Substrate dependencies
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

# Cumulus dependencies
cumulus-primitives = { git = "https://github.com/paritytech/cumulus", branch = "rococo-v1", default-features = false }

# Polkadot dependencies
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1" }
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1" }
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1" }

[features]
runtime-benchmarks = [
    "btc-parachain-runtime/runtime-benchmarks",
]
standalone = [
    "btc-parachain-runtime/standalone",
    "btc-parachain-service/standalone",
    "btc-parachain-rpc/standalone",
]
