[package]
authors = ["Interlay Ltd"]
build = "build.rs"
edition = "2018"
name = "btc-parachain"
version = "0.7.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "btc-parachain"

[build-dependencies.substrate-build-script-utils]
version = "2.0.0"

[dependencies]
structopt = "0.3.20"
log = "0.4.8"
codec = { package = "parity-scale-codec", version = "2.0.0" }
serde = { version = "1.0.101", features = ["derive"] }
hex-literal = "0.2.1"

# https://github.com/myrrlyn/funty/issues/3
funty = "=1.1"

# Parachain dependencies
btc-parachain-runtime = { path = "./runtime" }
btc-parachain-service = { path = "./service" }
btc-parachain-rpc = { path = "./rpc" }
bitcoin = { path = "../crates/bitcoin" }


# Substrate dependencies
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", features = ["wasmtime"] }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", features = ["wasmtime"] }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sc-tracing = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1" }

# Cumulus dependencies
cumulus-primitives = { package = "cumulus-primitives-core", git = "https://github.com/paritytech/cumulus", branch = "rococo-v1", optional = true }
cumulus-service = { package = "cumulus-client-service", git = "https://github.com/paritytech/cumulus", branch = "rococo-v1", optional = true }

# Polkadot dependencies
polkadot-primitives = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1", optional = true }
polkadot-cli = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1", optional = true }
polkadot-service = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1", optional = true }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot", branch = "rococo-v1", optional = true }

[features]
default = ["aura-grandpa"]
runtime-benchmarks = [
    "btc-parachain-runtime/runtime-benchmarks",
]
cumulus-polkadot = [
    "cumulus-primitives",
    "cumulus-service",
    "polkadot-primitives",
    "polkadot-cli",
    "polkadot-service",
    "polkadot-parachain",

    "btc-parachain-runtime/cumulus-polkadot",
    "btc-parachain-service/cumulus-polkadot",
    "btc-parachain-rpc/cumulus-polkadot",
]
aura-grandpa = [
    "btc-parachain-runtime/aura-grandpa",
    "btc-parachain-service/aura-grandpa",
    "btc-parachain-rpc/aura-grandpa",
]
disable-native-filter = [
    "btc-parachain-runtime/disable-native-filter",
]