[package]
name = "btc-relay"
version = '0.3.1'
authors = ["Interlay Ltd"]
edition = "2018"

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0.101'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.4'

[dependencies.frame-support]
default-features = false
version = '2.0.0'

[dependencies.frame-system]
default-features = false
version = '2.0.0'

[dependencies.sp-io]
default-features = false
version = '2.0.0'

[dependencies.sp-core]
default-features = false
version = '2.0.0'

[dependencies.sp-std]
default-features = false
version = '2.0.0'

[dependencies.primitive-types]
default-features = false
version = '0.7.2'
features= ['codec']

[dependencies.bitcoin]
default-features = false
path = '../bitcoin'

[dependencies.sla]
default-features = false
path = '../sla'

[dependencies.pallet-timestamp]
default-features = false
package = 'pallet-timestamp'
version = '2.0.0'

[dev-dependencies.exchange-rate-oracle]
default-features = false
path = '../exchange-rate-oracle'

[dev-dependencies.pallet-balances]
default-features = false
package = 'pallet-balances'
version = '2.0.0'

[dependencies.vault-registry]
default-features = false
path = '../vault-registry'

[dependencies.sp-arithmetic]
default-features = false
version = '2.0.0'

[dependencies.collateral]
default-features = false
path = '../collateral'

[dev-dependencies.treasury]
default-features = false
path = '../treasury'

[dev-dependencies.pallet-randomness-collective-flip]
default-features = false
package = 'pallet-randomness-collective-flip'
version = '2.0.0'

[dependencies.security]
default-features = false
path = '../security'

[dependencies.hex]
default-features = false
version = '0.4.2'

[dependencies.frame-benchmarking]
version = "2.0.0"
default-features = false
optional = true

[dev-dependencies]
mocktopus = '0.7.0'
frame-benchmarking = { version = "2.0.0" }

[dev-dependencies.sp-runtime]
default-features = false
version = '2.0.0'

[features]
default = ['std']
no-btc = []
std = [
    'serde',
    'codec/std',
    'frame-support/std',
    'frame-system/std',
	'sp-arithmetic/std',
    'sp-io/std',
    'sp-core/std',
    'pallet-timestamp/std',
    'sp-std/std',
    'primitive-types/std',
    'bitcoin/std',
    'sla/std',
	'vault-registry/std',
    'security/std',
    'hex/std',
    'frame-benchmarking/std',
]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
]
