[package]
name = "btc-relay"
version = "0.1.0"
authors = ["Interlay Ltd"]
edition = "2018"

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0.101'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.0.0'

[dependencies.frame-support]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.system]
default-features = false
package = 'frame-system'
version = '2.0.0-alpha.5'

[dependencies.sp-io]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.sp-core]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.timestamp]
default-features = false
package = 'pallet-timestamp'
version = '2.0.0-alpha.5'

[dependencies.sp-std]
default-features = false
version = '2.0.0-alpha.5'

[dependencies.primitive-types]
default-features = false
version = '0.7.0'
features= ['codec']

[dependencies.bitcoin]
default-features = false
path = '../bitcoin'

[dependencies.x-core]
default-features = false
path = '../x-core'

[dependencies.security]
default-features = false
path = '../security'

[dependencies.hex]
default-features = false
version = "0.4.0"

[dev-dependencies]
mocktopus = '0.7.0'

[dev-dependencies.sp-runtime]
default-features = false
version = '2.0.0-alpha.5'

[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'frame-support/std',
    'system/std',
    'sp-io/std',
    'sp-core/std',
    'timestamp/std',
    'sp-std/std',
    'primitive-types/std',
    'bitcoin/std',
    'x-core/std',
    'security/std',
    'hex/std',
]
