[package]
authors = ['Interlay Ltd']
edition = '2018'
name = 'btc-parachain-runtime'
version = '0.3.2'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
hex-literal = { version = "0.3.1", optional = true }

# Substrate dependencies
sp-std = { version = "2.0.0", default-features = false }
sp-api = { version = "2.0.0", default-features = false }
sp-io = { version = "2.0.0", default-features = false }
sp-version = { version = "2.0.0", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false }
sp-core = { version = "2.0.0", default-features = false }
sp-session = { version = "2.0.0", default-features = false }
sp-offchain = { version = "2.0.0", default-features = false }
sp-block-builder = { version = "2.0.0", default-features = false }
sp-transaction-pool = { version = "2.0.0", default-features = false }
sp-inherents = { version = "2.0.0", default-features = false }
sp-arithmetic = { version = "2.0.0", default-features = false }

frame-support = { version = "2.0.0", default-features = false }
frame-executive = { version = "2.0.0", default-features = false }
frame-system = { version = "2.0.0", default-features = false }
frame-benchmarking = { version = "2.0.0", default-features = false, optional = true }
frame-system-benchmarking = { version = "2.0.0", default-features = false, optional = true }
pallet-balances = { version = "2.0.0", default-features = false }
pallet-randomness-collective-flip = { version = "2.0.0", default-features = false }
pallet-timestamp = { version = "2.0.0", default-features = false }
pallet-sudo = { version = "2.0.0", default-features = false }
pallet-transaction-payment = { version = "2.0.0", default-features = false }

frame-system-rpc-runtime-api = { version = "2.0.0", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { version = "2.0.0", default-features = false }

# Consensus dependencies
pallet-aura = { version = "2.0.0", default-features = false }
pallet-grandpa = { version = "2.0.0", default-features = false }
sp-consensus-aura = { version = "0.8.0", default-features = false }

# Parachain dependencies
btc-relay = { path = "../../crates/btc-relay", default-features = false }
collateral = { path = "../../crates/collateral", default-features = false }
treasury = { path = "../../crates/treasury", default-features = false }
security = { path = "../../crates/security", default-features = false }
staked-relayers = { path = "../../crates/staked-relayers", default-features = false }
vault-registry = { path = "../../crates/vault-registry", default-features = false }
exchange-rate-oracle = { path = "../../crates/exchange-rate-oracle", default-features = false }
fee = { path = "../../crates/fee", default-features = false }
sla = { path = "../../crates/sla", default-features = false }
issue = { path = "../../crates/issue", default-features = false }
redeem = { path = "../../crates/redeem", default-features = false }
replace = { path = "../../crates/replace", default-features = false }
refund = { path = "../../crates/refund", default-features = false }

module-exchange-rate-oracle-rpc-runtime-api = { path = "../../crates/exchange-rate-oracle/rpc/runtime-api", default-features = false }
module-staked-relayers-rpc-runtime-api = { path = "../../crates/staked-relayers/rpc/runtime-api", default-features = false }
module-vault-registry-rpc-runtime-api = { path = "../../crates/vault-registry/rpc/runtime-api", default-features = false }
module-issue-rpc-runtime-api = { path = "../../crates/issue/rpc/runtime-api", default-features = false }
module-redeem-rpc-runtime-api = { path = "../../crates/redeem/rpc/runtime-api", default-features = false }
module-replace-rpc-runtime-api = { path = "../../crates/replace/rpc/runtime-api", default-features = false }
module-sla-rpc-runtime-api = { path = "../../crates/sla/rpc/runtime-api", default-features = false }
module-refund-rpc-runtime-api = { path = "../../crates/refund/rpc/runtime-api", default-features = false }

[dev-dependencies]
hex = '0.4.2'
mocktopus = '0.7.0'
serde_json = "1.0"

bitcoin = { path = "../../crates/bitcoin", default-features = false }
primitive-types = { version = "0.7.2", default-features = false, features = ["codec"] }

[build-dependencies.wasm-builder-runner]
package = 'substrate-wasm-builder-runner'
version = '1.0.5'

[features]
default = ["std"]
std = [
  "codec/std",
  "serde",
  "sp-api/std",
  "sp-std/std",
  "sp-io/std",
  "sp-core/std",
  "sp-runtime/std",
  "sp-version/std",
  "sp-offchain/std",
  "sp-session/std",
  "sp-block-builder/std",
  "sp-transaction-pool/std",
  "sp-inherents/std",
  "sp-arithmetic/std",

  "frame-support/std",
  "frame-executive/std",
  "frame-system/std",
  "frame-benchmarking/std",
  "frame-system-benchmarking/std",
  "pallet-balances/std",
  "pallet-randomness-collective-flip/std",
  "pallet-timestamp/std",
  "pallet-sudo/std",
  "pallet-transaction-payment/std",

  "frame-system-rpc-runtime-api/std",
  "pallet-transaction-payment-rpc-runtime-api/std",

  "pallet-aura/std",
  "pallet-grandpa/std",
  "sp-consensus-aura/std",

  "btc-relay/std",
  "collateral/std",
  "treasury/std",
  "security/std",
  "staked-relayers/std",
  "vault-registry/std",
  "exchange-rate-oracle/std",
  "fee/std",
  "sla/std",
  "refund/std",
  "issue/std",
  "redeem/std",
  "replace/std",
  "refund/std",

  "module-exchange-rate-oracle-rpc-runtime-api/std",
  "module-staked-relayers-rpc-runtime-api/std",
  "module-vault-registry-rpc-runtime-api/std",
  "module-issue-rpc-runtime-api/std",
  "module-redeem-rpc-runtime-api/std",
  "module-replace-rpc-runtime-api/std",
  "module-sla-rpc-runtime-api/std",
  "module-refund-rpc-runtime-api/std",
  ]
  runtime-benchmarks = [
  "hex-literal",

  "frame-benchmarking",
  "frame-system-benchmarking",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",

  "btc-relay/runtime-benchmarks",
  "exchange-rate-oracle/runtime-benchmarks",
  "issue/runtime-benchmarks",
  "redeem/runtime-benchmarks",
  "replace/runtime-benchmarks",
  "staked-relayers/runtime-benchmarks",
  "vault-registry/runtime-benchmarks",
  "fee/runtime-benchmarks",
]
