name: Continuous integration

permissions:
  contents: read

on: [pull_request]

jobs:
  test:
    name: Test Suite
    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - name: Install System Dependencies
        run: |
            sudo apt-get update && sudo apt-get install -y \
            cmake pkg-config libssl-dev git clang curl libc6-dev protobuf-compiler
      - name: Set variables
        run: |
            echo "TOOLCHAIN=$(rustup show active-toolchain | cut -d " " -f1)" >> $GITHUB_ENV
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.TOOLCHAIN }}
          components: rustfmt
      - name: cargo fmt
        run: |
          cargo fmt --all -- --check
      - name: cargo check
        run: |
          cargo check --release --workspace
      - name: cargo try-runtime check
        run: |
          cargo check --release --workspace --features try-runtime
      - name: cargo test
        run: |
          cargo test --release --workspace --features runtime-benchmarks
